steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/mle-fp/base:latest', '.' ]   #build the docker file found in the current directory
  timeout: 180s
  id: "Build Base Image"
  
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/mle-fp/base:latest']  
  timeout: 180s
  id: ["Push Base Image"]
  
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args:
  - "-c"
  - |
    echo "Docker Container Built And Pushed"  
    
#  - name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: "bash"
#   args: ['make', 'test_components']
#   timeout: 180s
#   id: "Make Tests"
#   waitFor: ["Push Base Image"]
  
#    - name: 'gcr.io/$PROJECT_ID/mle-fp/base:latest'
#   entrypoint: "python"
#   args: ['python', 'train_pipeline.py']
#   timeout: 180s
#   id: "Run Pipeline"
#   waitFor: ["Make Tests"]
